#!/bin/sh
BUCKET='godeploy'

cd deployed
if [ -f bin/godeploy ]; then
	SHA=$(./bin/godeploy -gitversion)
	echo $SHA
	if aws s3api head-object --bucket ${BUCKET} --key tags/production.tar.gz | grep $SHA > /dev/null; then
		echo "At Latest"
    	exit 0
	fi
fi

aws s3 cp s3://${BUCKET}/tags/production.tar.gz ./godeploy.tar.gz && tar -xvzf ./godeploy.tar.gz
